apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: f-registry:5000/redis_db
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6378
      hostPort: 6378
    resources:
      limits:
        cpu: "0.1"
    volumeMounts:
    - mountPath: /data
      name: data1
    #- mountPath: /data
    #  name: data2
    - mountPath: /usr/local/etc/redis
      name: config
  volumes:
    - name: data1
      #emptyDir: {}
      hostPath:
        path: /data/redis
    #- name: data2
      #hostPath:
        #path: /data/redis//usr/local/bin/redis-check-aof
    - name: config
      configMap:
        name: example-redis-config
        items:
        - key: redis-config
          path: redis.conf
