apiVersion: v1 
kind: Service 
metadata: 
  name: my-mysql 
  namespace: default 
  labels: 
    name: my-mysql 
spec: 
  type: NodePort
  ports: 
    - port: 3306 
      nodePort: 31089
  selector: 
    name: my-mysql
